import Head from "next/head";
// import { Header } from "../src/Layout/Header";
// import { Body } from "../src/Layout/Body";
import { Container } from "@mui/material";
import { HomePage } from "../src/home page/HomePage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Domine&family=Libre+Franklin:ital,wght@0,400;0,600;1,100&family=Tinos:wght@400;700&display=swap"
          rel="stylesheet"
        />

        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500&display=swap"
          rel="stylesheet"
        />

        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;500&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300&display=swap"
          rel="stylesheet"
        ></link>
        <link
          href="http://fonts.cdnfonts.com/css/itc-franklin-gothic-std"
          rel="stylesheet"
        ></link>
        <link href="http://fonts.cdnfonts.com/css/georgia" rel="stylesheet" />
      </Head>

      <Container style={{ padding: 0 }} maxWidth="xxl">
        {/* <Header />
        <Body /> */}

        <HomePage />
      </Container>
      <style jsx global>{`
        body {
          margin: 0px;
          padding: 0px;
        }
      `}</style>
    </>
  );
}
